[package]
name = "url_reputation"
version = "0.1.0"
edition = "2024"

[workspace]
members = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "url_reputation"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.28.0"
anyhow = "1.0.100"
url = "2.5.8"
