[package]
name = "url_reputation"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "url_reputation"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.101"
pyo3 = { version = "0.28.0", features = ["anyhow"] }
url = "2.5.8"
